### ISSUE TITLE
Respawning 

### ISSUE THREAD

**Issue by g2huda** [carterdy/CSC404GameDesign#7]
when archer at bottom dies, positions don't flip back 
ie when the archer at the bottom dies warrior is always back to bottom, then he will only do the turning while the archer will be moving back and forth

**Comment by carterdy** [comment]
Caused in the CentralPlayerController.  I think when the player hits the water, deactivating and reactivating resets which scripts are turned on by default (warrior bottom, archer top) but the central controller remembers whichever the previous orientation was and continues to just flip them.

I think the best fix would be to make a function to set the orientation, then call that in flip and call it when the player is spawned.

**Comment by g2huda** [comment]
issue is fixed
